# Generated by Django 5.0.1 on 2026-01-05 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type', models.CharField(choices=[('MEGA_SENA', 'Mega-Sena'), ('LOTOFACIL', 'Lotofácil'), ('QUINA', 'Quina'), ('DUPLA_SENA', 'Dupla Sena'), ('SUPER_SETE', 'Super Sete')], max_length=20, unique=True, verbose_name='Tipo de Loteria')),
                ('total_numbers', models.IntegerField(help_text='Total de números disponíveis para sorteio', verbose_name='Total de Números')),
                ('numbers_to_pick', models.IntegerField(help_text='Quantidade de números em cada aposta', verbose_name='Números a Escolher')),
                ('min_bet_numbers', models.IntegerField(blank=True, default=None, null=True, verbose_name='Mínimo de Números na Aposta')),
                ('max_bet_numbers', models.IntegerField(blank=True, default=None, null=True, verbose_name='Máximo de Números na Aposta')),
                ('primary_color', models.CharField(default='#009B3A', help_text='Cor hexadecimal para o tema da loteria', max_length=7, verbose_name='Cor Primária')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Configuração de Loteria',
                'verbose_name_plural': 'Configurações de Loterias',
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type', models.CharField(choices=[('MEGA_SENA', 'Mega-Sena'), ('LOTOFACIL', 'Lotofácil'), ('QUINA', 'Quina'), ('DUPLA_SENA', 'Dupla Sena'), ('SUPER_SETE', 'Super Sete')], db_index=True, max_length=20, verbose_name='Tipo de Loteria')),
                ('contest_number', models.IntegerField(db_index=True, verbose_name='Número do Concurso')),
                ('draw_date', models.DateField(db_index=True, verbose_name='Data do Sorteio')),
                ('numbers', models.JSONField(help_text='Lista de números sorteados', verbose_name='Números Sorteados')),
                ('numbers_second_draw', models.JSONField(blank=True, help_text='Para Dupla Sena', null=True, verbose_name='Números do 2º Sorteio')),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prêmio')),
                ('winners_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de Ganhadores')),
                ('accumulated', models.BooleanField(default=False, verbose_name='Acumulado')),
                ('next_estimated_prize', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimativa Próximo Concurso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['-contest_number'],
                'indexes': [models.Index(fields=['lottery_type', '-contest_number'], name='lotteries_d_lottery_77f50b_idx'), models.Index(fields=['lottery_type', '-draw_date'], name='lotteries_d_lottery_f97a92_idx')],
                'unique_together': {('lottery_type', 'contest_number')},
            },
        ),
        migrations.CreateModel(
            name='GenerationFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type', models.CharField(choices=[('MEGA_SENA', 'Mega-Sena'), ('LOTOFACIL', 'Lotofácil'), ('QUINA', 'Quina'), ('DUPLA_SENA', 'Dupla Sena'), ('SUPER_SETE', 'Super Sete')], max_length=20, verbose_name='Tipo de Loteria')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Filtro')),
                ('filter_config', models.JSONField(help_text='JSON com os parâmetros do filtro', verbose_name='Configuração do Filtro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_filters', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Filtro de Geração',
                'verbose_name_plural': 'Filtros de Geração',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type', models.CharField(choices=[('MEGA_SENA', 'Mega-Sena'), ('LOTOFACIL', 'Lotofácil'), ('QUINA', 'Quina'), ('DUPLA_SENA', 'Dupla Sena'), ('SUPER_SETE', 'Super Sete')], max_length=20, verbose_name='Tipo de Loteria')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Número')),
                ('frequency', models.IntegerField(default=0, help_text='Quantidade de vezes que o número foi sorteado', verbose_name='Frequência')),
                ('last_draw_contest', models.IntegerField(blank=True, help_text='Número do último concurso em que apareceu', null=True, verbose_name='Último Concurso')),
                ('delay', models.IntegerField(default=0, help_text='Concursos desde a última aparição', verbose_name='Atraso')),
                ('max_delay', models.IntegerField(default=0, help_text='Maior atraso histórico', verbose_name='Atraso Máximo')),
                ('average_delay', models.FloatField(default=0.0, help_text='Média de concursos entre aparições', verbose_name='Atraso Médio')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estatística de Número',
                'verbose_name_plural': 'Estatísticas de Números',
                'indexes': [models.Index(fields=['lottery_type', '-frequency'], name='lotteries_n_lottery_44484c_idx'), models.Index(fields=['lottery_type', '-delay'], name='lotteries_n_lottery_fbd674_idx')],
                'unique_together': {('lottery_type', 'number')},
            },
        ),
        migrations.CreateModel(
            name='UserCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_type', models.CharField(choices=[('MEGA_SENA', 'Mega-Sena'), ('LOTOFACIL', 'Lotofácil'), ('QUINA', 'Quina'), ('DUPLA_SENA', 'Dupla Sena'), ('SUPER_SETE', 'Super Sete')], max_length=20, verbose_name='Tipo de Loteria')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome da Combinação')),
                ('numbers', models.JSONField(help_text='Lista de números da combinação', verbose_name='Números')),
                ('session_key', models.CharField(blank=True, help_text='Para usuários não autenticados', max_length=40, null=True, verbose_name='Chave de Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Combinação do Usuário',
                'verbose_name_plural': 'Combinações dos Usuários',
                'ordering': ['-created_at'],
            },
        ),
    ]
